server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: userAuthentificaton-service
          uri: lb://USERAUTHENTIFICATON-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<remaining>.*), /$\{remaining}
        - id: hospitalManagement-service
          uri: lb://HOSPITALMANAGEMENT-SERVICE
          predicates:
            - Path=/api/hospital/**
          filters:
            - RewritePath=/api/hospital/(?<remaining>.*), /$\{remaining}
        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/api/reservations/**
          filters:
            - RewritePath=/api/reservations/(?<remaining>.*), /$\{remaining}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urls:
      - name: User Authentication Service
        url: /api/auth/v3/api-docs
      - name: Hospital Management Service
        url: /api/hospital/v3/api-docs
      - name: Reservation Service
        url: /api/reservations/v3/api-docs