server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Routes pour la documentation Swagger
        - id: userAuthentificaton-service-docs
          uri: lb://USERAUTHENTIFICATON-SERVICE
          predicates:
            - Path=/api/auth/v3/api-docs
          filters:
            - RewritePath=/api/auth/v3/api-docs, /v3/api-docs

        - id: hospitalManagement-service-docs
          uri: lb://HOSPITALMANAGEMENT-SERVICE
          predicates:
            - Path=/api/hospital/v3/api-docs
          filters:
            - RewritePath=/api/hospital/v3/api-docs, /v3/api-docs

        - id: reservation-service-docs
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/api/reservations/v3/api-docs
          filters:
            - RewritePath=/api/reservations/v3/api-docs, /v3/api-docs

        # Routes pour les autres endpoints
        - id: userAuthentificaton-service
          uri: lb://USERAUTHENTIFICATON-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: hospitalManagement-service
          uri: lb://HOSPITALMANAGEMENT-SERVICE
          predicates:
            - Path=/api/hospital/**

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/api/reservations/**

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urls:
      - name: User Authentication Service
        url: /api/auth/v3/api-docs
      - name: Hospital Management Service
        url: /api/hospital/v3/api-docs
      - name: Reservation Service
        url: /api/reservations/v3/api-docs
