spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user
    username: wael
    password: wael
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  mail:
    host: localhost
    port: 1025
    username: wael
    password: wael
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
  application:
    security:
      jwt:
        secret-key: DI3aKoVzJMbvAX7UQzdTRqqG7wxZg2wLZbaAyeJ8wF0=
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days
    mailing:
      frontend:
        activation-url: http://localhost:4200/activate-account

server:
  port: 8088